[package]
name = "reflect"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.24.1"  # egui framework for native GUI
chrono = "0.4.31"  # for date handling
serde = { version = "1.0", features = ["derive"] }  # for serialization
serde_json = "1.0"  # for JSON file handling 